BEGIN;

DROP TABLE IF EXISTS login_logs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS permission_policies;
DROP TABLE IF EXISTS policy_conditions;
DROP TABLE IF EXISTS policies;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;

COMMIT;
